### ISSUE TITLE
Cannot build with version 0.2.0

### ISSUE THREAD

**Issue by RayHughes** [kessejones/react-sweetalert2#6]
`$ npm i react-sweetalert2`

NPM installs successfully, but it fails to build. Tried in 2 environments.

```
Failed to compile.

index.js
Cannot find module: 'react-sweetalert2'. Make sure this package is installed.

You can install this package by running: npm install react-sweetalert2.
```

index.js 
`import SweetAlert2 from 'react-sweetalert2';`

**Comment by kessejones** [comment]
Thanks for reporting.
Check version 0.2.1
